<?php
/**
 * @file
 * Code for the VIU Simple FAQ feature.
 */

include_once 'viu_simple_faq.features.inc';

/**
 * Implements hook_views_api_alter()
 *
 * Views api is specified by features but we want to add the template directory.
 */
function viu_simple_faq_views_api_alter(&$apis) {
  if (!empty($apis['viu_simple_faq']) && $apis['viu_simple_faq']['api'] == '3.0') {
    $apis['viu_simple_faq']['template path'] = drupal_get_path('module', 'viu_simple_faq') . '/templates';
  }
}

/**
 * Implements hook_preprocess_HOOK
 *
 * We want to override the panels_bootstrap_pane hook and inject some HTML (for the fa-icon)
 */
function viu_simple_faq_preprocess_panels_bootstrap_pane(&$vars) {
  if ($vars['title'] == "FAQ Categories") {
    $vars['title'] = '<span aria-hidden="true" class="icon-question"></span>&nbsp;' . $vars['title'];
  }
}

/**
 * Implements hook_form_alter().
 *
 * @todo We will use this hook to limit the node edit form from allowing the user to select anything except FAQ Categories
 */
function viu_simple_faq_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == "oa_section_node_form" && $form['#node_edit_form']) {
    //sdpm($form);
    //sdpm($form_state);
    //dpm($form_id);
    //sdpm($form_state['node']);
    //$section_term_id = $form_state['node']->field_oa_section['und']['0']['tid'];
    //$taxonomy = taxonomy_term_load($section_term_id);
    //dpm($taxonomy);
    //WORKING HERE
  }
}
